#!/usr/bin/env bash
if [ $# -eq 0 ]
	then
		echo "VideoWall v1.0.0, Video Wallpaper Wrapper for VLC."
		echo "Copyright (c) 2017 Antony Jr."
		echo " "
		echo "Usage: VideoWall [VLC OPTIONS] [VIDEO FILES / FOLDER WITH VIDEOS]"
		exit -1
fi

VlcInstalled=$(command -v cvlc);
kstart5=$(command -v kstart5);
kstart=$(command -v kstart);

if [ $VlcInstalled ]
	then
		1>/dev/null 2>/dev/null killall vlc;
		if [ $kstart ]
			then
				kstart --alldesktops -- 1>/dev/null 2>/dev/null cvlc --video-wallpaper "$*" &
		elif [ $kstart5 ]
			then
				kstart5 --alldesktops -- 1>/dev/null 2>/dev/null cvlc --video-wallpaper "$*" &
		else
				1>/dev/null 2>/dev/null cvlc --video-wallpaper "$*" & 
		fi
	else
		exit -1
fi
